[workspace]

members = [
    "refresh-iceberg-datafusion-dashbook",
    "refresh-iceberg-datafusion-sql",
]

[workspace.dependencies]
datafusion_iceberg = "0.3"
dashtool-common = "0.1"
iceberg-rust = "0.3"
object_store = { version = "0.9", features = ["cloud"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
