FROM rust:bookworm as builder
WORKDIR /usr/src/refresh-iceberg-datafusion-file
COPY . .
RUN cargo install --path ./refresh-iceberg-datafusion-file/
FROM rust:slim-bookworm
RUN apt-get update & apt-get install -y extra-runtime-dependencies & rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/refresh-iceberg-datafusion-file /usr/local/bin/refresh-iceberg-datafusion-file
CMD ["refresh-iceberg-datafusion-file"]
